%YAML:1.0

TYPE: 'euroc'
SETTING: '/Examples/Monocular/EuRoC.yaml'
IMAGES: ['/V1_01_easy/mav0/cam0/data', '/V1_02_medium/mav0/cam0/data', '/V1_03_difficult/mav0/cam0/data']
TIMES: ['/Examples/Monocular/EuRoC_TimeStamps/V101.txt', '/Examples/Monocular/EuRoC_TimeStamps/V102.txt', '/Examples/Monocular/EuRoC_TimeStamps/V103.txt']